def postproc(param_model, prediction, y, remove_warm_up: bool = False) -> dict:
    """Warm-up period must be excluded: warm-up period is usually
        equals to infected_to_recovered_or_death_time, we need to remove it since
        it is not generated by the model (e.g., people gradually die over time). In contrast,
        the death after warm-up will suddenly emerge from the initial infection.

    Args:
        param_model (_type_): _description_
        prediction (_type_): _description_
        y (_type_): _description_
    """
    output = {
        "pred": prediction["prediction"][0, :],
        "all_records": prediction["all_records"],
        "y": y[0, :, 0],
    }
    if remove_warm_up:
        infected_to_recovered_or_death_time_index = param_model.learnable_param_order.index(
            "infected_to_recovered_or_death_time"
        )

        exposed_to_infected_time_index = param_model.learnable_param_order.index(
            "exposed_to_infected_time"
        )
        warm_up_period_end = (
            param_model.max_values[infected_to_recovered_or_death_time_index]
            + param_model.max_values[exposed_to_infected_time_index]
        )

        output["pred"] = output["pred"][int(warm_up_period_end.item()) :]

        if output["all_records"] is not None:
            output["all_records"] = output["all_records"][int(warm_up_period_end.item()) :]

        output["y"] = output["y"][int(warm_up_period_end.item()) :]

    return output
