from model import REMOVE_WARM_UP_TIMESTEPS


def postproc(prediction, y) -> dict:
    """Warm-up period must be excluded: warm-up period is usually
        equals to infected_to_recovered_or_death_time, we need to remove it since
        it is not generated by the model (e.g., people gradually die over time). In contrast,
        the death after warm-up will suddenly emerge from the initial infection.

    Args:
        param_model (_type_): _description_
        prediction (_type_): _description_
        y (_type_): _description_
    """
    output = {
        "pred": prediction["prediction"][0, :],
        "all_records": prediction["all_records"],
        "y": y[0, :, 0],
        "all_target_indices": prediction["all_target_indices"],
        "agents_area": prediction["agents_area"],
        "agents_ethnicity": prediction["agents_ethnicity"],
    }
    if REMOVE_WARM_UP_TIMESTEPS is not None:
        output["pred"] = output["pred"][REMOVE_WARM_UP_TIMESTEPS:]

        if output["all_records"] is not None:
            output["all_records"] = output["all_records"][REMOVE_WARM_UP_TIMESTEPS:]

        output["y"] = output["y"][REMOVE_WARM_UP_TIMESTEPS:]

    return output
